# Generated by Django 3.0 on 2020-05-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fun', '0002_follow_like_save_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
